export const ActionTypes = {

    //saved all actions in one file - easy to import and use
    //however not sure it's good, I incline ActionTypes should be splitted by stores as well
    GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST',
    GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS',
    GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED',
    SET_ACTIVE_INGREDIENT: 'SET_ACTIVE_INGREDIENT',
    SHOW_INGREDIENT_DETAILS: 'SHOW_INGREDIENT_DETAILS',

    UPDATE_CART: 'UPDATE_CART',
    
    CREATE_NEW_ORDER_REQUEST: 'CREATE_NEW_ORDER_REQUEST',
    CREATE_NEW_ORDER_SUCCESS: 'CREATE_NEW_ORDER_SUCCESS',
    CREATE_NEW_ORDER_FAILED: 'CREATE_NEW_ORDER_FAILED',
    SHOW_ORDER_DETAILS: 'SHOW_ORDER_DETAILS',
    CLOSE_ORDER: 'CLOSE_ORDER',    
    SORT_FILLINGS_ORDER: 'SORT_FILLINGS_ORDER'

};